version: 2

sources:
  - name: "sources"
    database: "taxi"
    schema: "yellow_trip"
    tags: ["sources"]
    description: "{{ doc('sources') }}"

    tables:
      - name: "yellow_2018_01"
        description: "yellow taxi data for year 2018 month 01"
      - name: "yellow_2018_02"
        description: "yellow taxi data for year 2018 month 02"
      - name: "yellow_2018_03"
        description: "yellow taxi data for year 2018 month 03"
      - name: "yellow_2018_04"
        description: "yellow taxi data for year 2018 month 04"
      - name: "yellow_2018_05"
        description: "yellow taxi data for year 2018 month 05"
      - name: "yellow_2018_06"
        description: "yellow taxi data for year 2018 month 06"
      - name: "yellow_2018_07"
        description: "yellow taxi data for year 2018 month 07"
      - name: "yellow_2018_08"
        description: "yellow taxi data for year 2018 month 08"
      - name: "yellow_2018_09"
        description: "yellow taxi data for year 2018 month 09"
      - name: "yellow_2018_10"
        description: "yellow taxi data for year 2018 month 10"
      - name: "yellow_2018_11"
        description: "yellow taxi data for year 2018 month 11"
      - name: "yellow_2018_12"
        description: "yellow taxi data for year 2018 month 12"
      - name: "yellow_2019_01"
        description: "yellow taxi data for year 2019 month 01"
      - name: "yellow_2019_02"
        description: "yellow taxi data for year 2019 month 02"
      - name: "yellow_2019_03"
        description: "yellow taxi data for year 2019 month 03"
      - name: "yellow_2019_04"
        description: "yellow taxi data for year 2019 month 04"
      - name: "yellow_2019_05"
        description: "yellow taxi data for year 2019 month 05"
      - name: "yellow_2019_06"
        description: "yellow taxi data for year 2019 month 06"
      - name: "yellow_2019_07"
        description: "yellow taxi data for year 2019 month 07"
      - name: "yellow_2019_08"
        description: "yellow taxi data for year 2019 month 08"
      - name: "yellow_2019_09"
        description: "yellow taxi data for year 2019 month 09"
      - name: "yellow_2019_10"
        description: "yellow taxi data for year 2019 month 10"
      - name: "yellow_2019_11"
        description: "yellow taxi data for year 2019 month 11"
      - name: "yellow_2019_12"
        description: "yellow taxi data for year 2019 month 12"
      - name: "yellow_2020_01"
        description: "yellow taxi data for year 2020 month 01"
      - name: "yellow_2020_02"
        description: "yellow taxi data for year 2020 month 02"
      - name: "yellow_2020_03"
        description: "yellow taxi data for year 2020 month 03"
      - name: "yellow_2020_04"
        description: "yellow taxi data for year 2020 month 04"
      - name: "yellow_2020_05"
        description: "yellow taxi data for year 2020 month 05"
      - name: "yellow_2020_06"
        description: "yellow taxi data for year 2020 month 06"
      - name: "yellow_2020_07"
        description: "yellow taxi data for year 2020 month 07"
      - name: "yellow_2020_08"
        description: "yellow taxi data for year 2020 month 08"
      - name: "yellow_2020_09"
        description: "yellow taxi data for year 2020 month 09"
      - name: "yellow_2020_10"
        description: "yellow taxi data for year 2020 month 10"
      - name: "yellow_2020_11"
        description: "yellow taxi data for year 2020 month 11"
      - name: "yellow_2020_12"
        description: "yellow taxi data for year 2020 month 12"
      - name: "yellow_2021_01"
        description: "yellow taxi data for year 2021 month 01"
      - name: "yellow_2021_02"
        description: "yellow taxi data for year 2021 month 02"
      - name: "yellow_2021_03"
        description: "yellow taxi data for year 2021 month 03"
      - name: "yellow_2021_04"
        description: "yellow taxi data for year 2021 month 04"
      - name: "yellow_2021_05"
        description: "yellow taxi data for year 2021 month 05"
      - name: "yellow_2021_06"
        description: "yellow taxi data for year 2021 month 06"
      - name: "yellow_2021_07"
        description: "yellow taxi data for year 2021 month 07"
      - name: "yellow_2021_08"
        description: "yellow taxi data for year 2021 month 08"
      - name: "yellow_2021_09"
        description: "yellow taxi data for year 2021 month 09"
      - name: "yellow_2021_10"
        description: "yellow taxi data for year 2021 month 10"
      - name: "yellow_2021_11"
        description: "yellow taxi data for year 2021 month 11"
      - name: "yellow_2021_12"
        description: "yellow taxi data for year 2021 month 12"
      - name: "yellow_2022_01"
        description: "yellow taxi data for year 2022 month 01"
      - name: "yellow_2022_02"
        description: "yellow taxi data for year 2022 month 02"
      - name: "yellow_2022_03"
        description: "yellow taxi data for year 2022 month 03"
      - name: "yellow_2022_04"
        description: "yellow taxi data for year 2022 month 04"
      - name: "yellow_2022_05"
        description: "yellow taxi data for year 2022 month 05"
      - name: "yellow_2022_06"
        description: "yellow taxi data for year 2022 month 06"
      - name: "yellow_2022_07"
        description: "yellow taxi data for year 2022 month 07"
      - name: "yellow_2022_08"
        description: "yellow taxi data for year 2022 month 08"
      - name: "yellow_2022_09"
        description: "yellow taxi data for year 2022 month 09"
      - name: "yellow_2022_10"
        description: "yellow taxi data for year 2022 month 10"
      - name: "yellow_2022_11"
        description: "yellow taxi data for year 2022 month 11"
      - name: "yellow_2022_12"
        description: "yellow taxi data for year 2022 month 12"
      - name: "yellow_2023_01"
        description: "yellow taxi data for year 2023 month 01"
      - name: "yellow_2023_02"
        description: "yellow taxi data for year 2023 month 02"
      - name: "yellow_2023_03"
        description: "yellow taxi data for year 2023 month 03"
      - name: "yellow_2023_04"
        description: "yellow taxi data for year 2023 month 04"
      - name: "yellow_2023_05"
        description: "yellow taxi data for year 2023 month 05"
      - name: "yellow_2023_06"
        description: "yellow taxi data for year 2023 month 06"
      - name: "yellow_2023_07"
        description: "yellow taxi data for year 2023 month 07"
      - name: "yellow_2023_08"
        description: "yellow taxi data for year 2023 month 08"
      - name: "yellow_2023_09"
        description: "yellow taxi data for year 2023 month 09"
      - name: "yellow_2023_10"
        description: "yellow taxi data for year 2023 month 10"
      - name: "yellow_2023_11"
        description: "yellow taxi data for year 2023 month 11"
      - name: "yellow_2023_12"
        description: "yellow taxi data for year 2023 month 12"
      - name: "yellow_2024_01"
        description: "yellow taxi data for year 2024 month 01"
      - name: "yellow_2024_02"
        description: "yellow taxi data for year 2024 month 02"
      - name: "yellow_2024_03"
        description: "yellow taxi data for year 2024 month 03"
      - name: "yellow_2024_04"
        description: "yellow taxi data for year 2024 month 04"
      - name: "yellow_2024_05"
        description: "yellow taxi data for year 2024 month 05"
      - name: "yellow_2024_06"
        description: "yellow taxi data for year 2024 month 06"
      - name: "yellow_2024_07"
        description: "yellow taxi data for year 2024 month 07"
      - name: "yellow_2024_08"
        description: "yellow taxi data for year 2024 month 08"
      - name: "yellow_2024_09"
        description: "yellow taxi data for year 2024 month 09"
      - name: "yellow_2024_10"
        description: "yellow taxi data for year 2024 month 10"
      - name: "yellow_2024_11"
        description: "yellow taxi data for year 2024 month 11"
      - name: "yellow_2024_12"
        description: "yellow taxi data for year 2024 month 12"
      - name: "yellow_2025_01"
        description: "yellow taxi data for year 2025 month 01"
      - name: "yellow_2025_02"
        description: "yellow taxi data for year 2025 month 02"
